version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - ./:/var/www/html/

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  composer:
    image: composer:1.8
    volumes:
      - .:/app
    command: install --ignore-platform-reqs